[package]
name = "gui_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
filmr = { path = "../../" }
eframe = "0.33.3"
egui = "0.33.3"
image = "0.24"
rfd = "0.17.2"
egui_plot = "0.34.0"
crossbeam-channel = "0.5.15"
